# Generated by Django 5.1.6 on 2025-03-03 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulations', '0003_alter_simulation_scenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sender', models.CharField(choices=[('user', 'Utilisateur'), ('bot', 'Chatbot')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='simulations.simulation')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
