# Generated by Django 5.1.6 on 2025-03-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='scenario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
